// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKQ0zzAfTDYDK5FPDBGHSJfxacwNh308',
    appId: '1:1030068367887:web:77d04b3dbbd6f754a1a97a',
    messagingSenderId: '1030068367887',
    projectId: 'midouno-c6251',
    authDomain: 'midouno-c6251.firebaseapp.com',
    storageBucket: 'midouno-c6251.firebasestorage.app',
    measurementId: 'G-44FXXH47E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQeUraYOYc9kUP8N_ABwlsUaFNRa4Ia7M',
    appId: '1:1030068367887:android:660ef61c30ca5401a1a97a',
    messagingSenderId: '1030068367887',
    projectId: 'midouno-c6251',
    storageBucket: 'midouno-c6251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNC7ZM77zTqRXj-u9c7H9suQztOT6IR8A',
    appId: '1:1030068367887:ios:d6da107c555e36b0a1a97a',
    messagingSenderId: '1030068367887',
    projectId: 'midouno-c6251',
    storageBucket: 'midouno-c6251.firebasestorage.app',
    iosBundleId: 'com.example.midounou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNC7ZM77zTqRXj-u9c7H9suQztOT6IR8A',
    appId: '1:1030068367887:ios:d6da107c555e36b0a1a97a',
    messagingSenderId: '1030068367887',
    projectId: 'midouno-c6251',
    storageBucket: 'midouno-c6251.firebasestorage.app',
    iosBundleId: 'com.example.midounou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJKQ0zzAfTDYDK5FPDBGHSJfxacwNh308',
    appId: '1:1030068367887:web:979547c8527b0e0fa1a97a',
    messagingSenderId: '1030068367887',
    projectId: 'midouno-c6251',
    authDomain: 'midouno-c6251.firebaseapp.com',
    storageBucket: 'midouno-c6251.firebasestorage.app',
    measurementId: 'G-JJSQ694NK6',
  );
}
